isdevelopment=true
server.port=5179
spring.datasource.url=jdbc:sqlserver://localhost:1434;encrypt=true;trustServerCertificate=true;integratedSecurity=true;databaseName=JimmysFoodzillaJavaDB
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect
auth0.domain=dev-f0vakdckhtwh0dl8.us.auth0.com
auth0.audience=https://jimmys/api
auth0.m2maudience=https://jimmys/registeruser/api
auth0.m2m_clientid=Jifzocq6ozlob8VlGi2WeWKRz4PYPaG3
auth0.m2m_clientsecret=hA5k2t5mAPpKUfEfKQbI7FE3RjMx3wXO_TWYlXCasXL1sWPFivsPYXT37Rbkz6d9
ngrok.url=solely-useful-grouse.ngrok-free.app