server.port=5179
spring.datasource.url=jdbc:sqlserver://localhost:1434;encrypt=true;trustServerCertificate=true;integratedSecurity=true;databaseName=JimmysFoodzillaJavaDB
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect